apiVersion: v1
kind: Secret
metadata:
  name: hmengine-db-secret
  namespace: default
  labels:
    app: hmengine-db
    release: hmengine-db
data:
  # 密码需要base64加密
  root-password: UGFTc1dvUmQxMjM0
type: Opaque
