apiVersion: v1
kind: Service
metadata:
  name: hmengine-db-svc
  namespace: default
  labels:
    app: hmengine-db
    release: hmengine-db
spec:
  ports:
    - name: db
      protocol: TCP
      port: 6000
      targetPort: 6000
  selector:
    app: hmengine-db
    release: hmengine-db
  type: ClusterIP
  sessionAffinity: None
